version: "3.7"

services:
  ssh:
    container_name: ssh
    hostname: ssh
    build:
      context: .
      dockerfile: ./alpine/Dockerfile
    restart: unless-stopped
    environment:
      - SSH_USE_PASSWORD=false
    volumes:
      - "./data:/data"
    networks:
      - noInternet
    security_opt:
      - "no-new-privileges:true"
  tunnel:
    container_name: tunnel
    hostname: tunnel
    build: "./tunnel"
    restart: unless-stopped
    environment:
      - SSH_HOST=ssh
      - SSH_PORT=22
      - SSH_USER=sshUser
      - SSH_PASSWORD=sshUser
      - SSH_USE_PASSWORD=false
    volumes:
      - "./data:/data"
    ports:
      - "2222:22"
    networks:
      - noInternet
      - internet
    security_opt:
      - "no-new-privileges:true"


networks:
  noInternet:
    internal: true
  internet:
    internal: false